# -*- coding: utf-8 -*-
"""Copy of Copy of Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T7URXDdhKKxY7erX_LbMkNIlrlzF7S5g

1. Write a function that takes a number and returns an array of its digits.
"""

def return_list_of_digits(number_1):
    c = str(number_1)
    int_list = []
    for i in range(len(c)):
        int_list.append(int(c[i]))
    return int_list
input_number = input("Enter the number: ")
list_of_digits = return_list_of_digits(input_number)
print(list_of_digits)

"""2. Write a function that translates a text to Pig Latin and back. English is translated to Pig Latin by taking the first letter of every word, moving it to the end of the word, and adding "ay".  For example, "hello to kudoswall" becomes "ellohay otay udoswallkay"."""

def pig_latin(text):
  words = text.split()
  pigged_text = []

  for word in words:
    word = word[1:] + word[0] + 'ay'
    pigged_text.append(word)

  return ' '.join(pigged_text)

print(pig_latin("hello to kudoswall"))

"""3. Write a function that rotates an array by k elements. For example, [1,2,3,4,5,6] rotated by two becomes [3,4,5,6,1,2]. Try solving this without creating a copy of the array."""

def rotate_list(lst, k):
  k = k % len(lst)
  for i in range(k):
    lst.insert(0, lst.pop())

"""4. Write a function to alternate the case of the characters in the string; i.e., each lowercase letter becomes uppercase and each uppercase letter becomes lowercase. For example, altERnaTIng cAsE becomes ALTerNAtiNG CaSe

"""

def alternate_case(s):
  alternated_case = ""
  for ch in s:
    if ch.isupper():
      alternated_case += ch.lower()
    elif ch.islower():
      alternated_case += ch.upper()
    else:
      alternated_case += ch
  return alternated_case